IBC/config/routes.rb
Rails.application.routes.draw do
  get 'alumnos' => 'alumnos#index'

  get 'alumnos/new'

  get 'alumnos/show'

  get 'alumnos/destroy'

  get 'alumnos/edit'

  resources :alumnos

  get '/computacion' => 'computacion#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'ibc' => 'principal#index'

  get 'usuario' => 'users#index'
  get 'signup' => 'users#new'
  resources :users

  root 'principal#index'

end

IBC/app/models/alumno.rb
class Alumno < ActiveRecord::Base
	belongs_to :cat_estatus
end

IBC/app/models/cat_estatus.rb
class CatEstatus < ActiveRecord::Base

end

IBC/app/models/user.rb
class User < ActiveRecord::Base
	 has_secure_password
	 validates :password, :confirmation => { message: 'password' }
end

IBC/app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  def index
    @alumno = Alumno.all
  end

  def new
    @alumno = Alumno.new
  end

  def create
    @alumno = Alumno.new(alumno_params)
    if @alumno.save
      redirect_to '/alumnos'
    else
      render 'new'
    end
  end

  def show
    @alumno = Alumno.find(params[:id])
  end

  def destroy
    @alumno = Alumno.find(params[:id])
    @alumno.destroy
    redirect_to '/alumnos'
  end

  def edit
    @alumno = Alumno.find(params[:id])
  end

  def update
    @alumno = Alumno.find(params[:id])
    if @alumno.update(alumno_params)
      redirect_to '/alumnos'
    else
      render 'edit'
    end
  end

  private
    def alumno_params
      params.require(:alumno).permit(:nombre_a, :app, :apm, :direccion, :fecha_nac, :telefono, :email)
    end
    
end

IBC/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	helper_method :current_user 

	def current_user
		#session[:user_id] = nil 	
	  @current_user ||= User.find(session[:user_id]) if session[:user_id] 
	end

	def require_user 
  		redirect_to '/login' unless current_user 
	end
end

IBC/app/controllers/computacion_controller.rb
class ComputacionController < ApplicationController
  before_action :require_user, only: [:index, :show]
  
  def index
  end
end

IBC/app/controllers/principal_controller.rb
class PrincipalController < ApplicationController

	before_action :require_user, only: [:index, :show]
	
	def index
	end

end

IBC/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  	
  	def new
  	end

 	def create
	  @user = User.find_by(nombre: params[:session][:nombre])
	  #@user = User.all
	  if @user && @user.authenticate(params[:session][:password])
	    session[:user_id] = @user.id
	    redirect_to '/ibc'
	  else
	    redirect_to 'login'
	  end 
	end

	def destroy 
	  session[:user_id] = nil 
	  redirect_to '/login' 
	end
end

IBC/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = User.all
	end

	def new
		@user = User.new
	end

	def create 
		if @use = User.find_by(params[:nombre])
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print @use.nombre
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			print "***************************************"
			@user = User.new(user_params)	  
			if @user.save 
			#session[:user_id] = @user.id 
				redirect_to '/usuario' 
			else 
				redirect_to '/signup' 
			end
		else
			redirect_to '/usuario'
		end 
	end

	private
	  def user_params
	    params.require(:user).permit(:nombre, :apellido, :password)
	  end
end

IBC/app/helpers/alumnos_helper.rb
module AlumnosHelper
end

IBC/app/helpers/application_helper.rb
module ApplicationHelper
end

IBC/app/helpers/computacion_helper.rb
module ComputacionHelper
end

IBC/app/helpers/principal_helper.rb
module PrincipalHelper
end

IBC/app/helpers/sessions_helper.rb
module SessionsHelper
end

IBC/app/helpers/users_helper.rb
module UsersHelper
end

IBC/app/views/alumnos/_form.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/computacion">Inicio</a></li>
        <li><a href="/alumnos">Alumnos</a></li>
        <li><a href="#section2">Materias</a></li>
        <li><a href="#section3">Calificaciones</a></li>
        <li><a href="#section3">Couotas</a></li>
      </ul><br>      
    </div>

    <div class="col-sm-9">
	     <h4><small>Cosas de Alumnos</small></h4>
	     <hr>
	     <h2>Alumnos</h2>
	     <h5><span class="glyphicon glyphicon-time"></span> Jueves 16 Junio 2016</h5>

		<div class="form-group">
			<%= form_for @alumno do |f| %>
				<% if @alumno.errors.any? %>
			<div id="error_explanation">
			<h2><%= pluralize(@alumno.errors.count, "error") %> prohibited
		      	this alumno from being saved:</h2>
				<ul><% @alumno.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
				</ul>
			</div>
			<% end %>
			<div class="list-group-item list-group-item-info col-sm-5">
				<p>
					<%= f.label :Nombre %><br>
					<%= f.text_field :nombre_a %>
				</p>
				<p>
					<%= f.label :Apellido_paterno %><br>
					<%= f.text_field :app %>
				</p>
				<p>
					<%= f.label :Apellido_Materno %><br>
					<%= f.text_field :apm %>
				</p>
				<p>
					<%= f.label :Dirección %><br>
					<%= f.text_field :direccion %>
				</p>
			</div>
			<div class="list-group-item list-group-item-info col-sm-5">
				<p>
					<%= f.label :Fecha_Nacimiento, class:"date"%><br>
					<%= f.date_field :fecha_nac %>
				</p>
				<p>
					<%= f.label :Telefono %><br>
					<%= f.text_field :telefono %>
				</p>
				<p>
					<%= f.label :Email %><br>
					<%= f.email_field :email %>
				</p>
				<p>
					<%= f.submit 'Guardar', class:"btn btn-success"%>
					<a href="/alumnos" class="btn btn-warning">Cancelar</a>
				</p>
			</div>
			<% end %>
		</div>
    </div>
  </div>
</div>

IBC/app/views/alumnos/destroy.html.erb
<h1>Alumnos#destroy</h1>
<p>Find me in app/views/alumnos/destroy.html.erb</p>

IBC/app/views/alumnos/edit.html.erb
<%= render 'form' %>

IBC/app/views/alumnos/index.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/computacion">Inicio</a></li>
        <li><a href="/alumnos">Alumnos</a></li>
        <li><a href="#section2">Materias</a></li>
        <li><a href="#section3">Calificaciones</a></li>
        <li><a href="#section3">Couotas</a></li>
      </ul><br>      
    </div>
    <div class="col-sm-9">
      <h4><small>Cosas de Alumnos</small></h4>
      <hr>
      <h2>Alumnos</h2>
      <h5><span class="glyphicon glyphicon-time"></span> Jueves 16 Junio 2016</h5>
      <%= link_to 'Nuevo Alumno', '/alumnos/new',class:"btn btn-primary" %>
      <table class="table">
        <tr>
          <th>Nombre</th>
          <th>Apellido Paterno</th>
          <th>Apellido Materno</th>
          <th>Fecha Nacimiento</th>
          <th>Direccion</th>
          <th>Telefono</th>
          <th>Email</th>
        </tr>
        <%@alumno.each do |a|%>
          <tr>
            <td><%=a.nombre_a%></td>
            <td><%=a.app%></td>
            <td> <%=a.apm%></td>
            <td><%=a.telefono%></td>
            <td><%= link_to 'Mostrar', alumno_path(a), class:"btn btn-info"%></td>
            <td><%= link_to 'Editar', edit_alumno_path(a), class:"btn btn-warning"%></td>
            <td><%= link_to 'Eliminar', alumno_path(a), method: :delete, data: { confirm: '¿Estas seguro?'},class:"btn btn-danger" %>            
          </tr>
        <%end%>
      </table>
    </div>
  </div>
</div>

IBC/app/views/alumnos/new.html.erb
<%= render 'form' %>

IBC/app/views/alumnos/show.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/computacion">Inicio</a></li>
        <li><a href="/alumnos">Alumnos</a></li>
        <li><a href="#section2">Materias</a></li>
        <li><a href="#section3">Calificaciones</a></li>
        <li><a href="#section3">Couotas</a></li>
      </ul><br>      
    </div>

    <div class="col-sm-9">
	    <h4><small>Cosas de Alumnos</small></h4>
	    <hr>
	    <h2>Alumnos</h2>
	    <h5><span class="glyphicon glyphicon-time"></span> Jueves 16 Junio 2016</h5>
		<div class="list-group-item list-group-item-info col-sm-5">
			<p >
				<strong>Nombre</strong><br>
				<%= @alumno.nombre_a %>
			</p>
			<p>
				<strong>Apellido Paterno</strong><br>
				<%= @alumno.app %>
			</p>
			<p>
				<strong>Apellido Materno</strong><br>
				<%= @alumno.apm %>
			</p>
			<p>
				<strong>Dirección</strong><br>
				<%= @alumno.direccion %>
			</p>
		</div>
		<div class="list-group-item list-group-item-info col-sm-5">
			<p>
				<strong>Fecha Nacimiento</strong><br>
				<%= @alumno.fecha_nac %>
			</p>
			<p>
				<strong>Telefono</strong><br>
				<%= @alumno.telefono %>
			</p>
			<p>
				<strong>Email</strong><br>
				<%= @alumno.email %>
			</p>
		</div>
	</div>
  </div>
</div>

IBC/app/views/computacion/index.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/computacion">Inicio</a></li>
        <li><a href="/alumnos">Alumnos</a></li>
        <li><a href="#section2">Materias</a></li>
        <li><a href="#section3">Calificaciones</a></li>
        <li><a href="#section3">Couotas</a></li>
      </ul><br>      
    </div>
    
    <div class="col-sm-9">
      <h4><small>Computación</small></h4>
      <hr>
      <h2>--------</h2>
      <h5><span class="glyphicon glyphicon-time"></span> Miercoles 16 Junio 2016</h5>
      

      <h5><span class="label label-danger">Food</span> <span class="label label-primary">Agregar Alumno</span></h5><br>
      <p>Food is my passion. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      <br><br>
      
      
      
    </div>

  </div>
</div>

IBC/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IBC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta content="text/html; charset=utf-8"/>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %> 
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/ibc">IBC</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Belleza</a></li>
      <li class="active"><a href="/computacion">Computación</a></li>
      <li class="active"><a href="#">Registrar Instructor</a></li>      
      <li class="active"><a href="/usuario">Usuario</a></li>        

    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a style="text-transform: capitalize"><span class="glyphicon glyphicon-user"></span><%= current_user.nombre %></a></li>      
      <li><%= link_to "Cerrar", logout_path, method: "delete" %></li>
    </ul>
  </div>
</nav>
<% end %>


<%= yield %>

  <% if current_user %> 
    <div id="footer">
      <div class="navbar navbar-fixed-bottom">
        <div class="navbar-inner">
          <div class="container">
            <footer class="container-fluid text-center text-info">
              <p>Guerrero 7 Dolores Hidalgo</p>
              <p>Instituto de Belleza y Computación</p>
              <p>l_farias@hotmail.com</p>
              <p><a href="https://www.facebook.com/BELLEZAYCOMPUTACION/" target="_blank">Facebook</a></p>
            </footer>
          </div>
        </div>
      </div>
    </div>
  <% end %>     
</body>
</html>

IBC/app/views/principal/index.html.erb
<h1>Pagina de inicio</h1>

IBC/app/views/users/index.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/usuario">Inicio </a></li>
        <li><a href="/signup">Registrar usuario</a></li>
        <li><a href="#section2">Configuraciones</a></li>
      </ul><br>      
    </div>

    <!-- Contenido -->
    <div class="col-sm-2 sidenav ">
      <h1>Usuarios</h1>
    </div>
    <div class="col-sm-2 sidenav list-group-item">
      <% @user.each do |u| %>
      <h1><kbd><%= u.nombre %></kbd></h1>
      <% end %>
    </div>
  </div>
</div>

IBC/app/views/users/new.html.erb
<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-2 sidenav">
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="/usuario">Inicio</a></li>
        <li><a href="/signup">Registrar usuario</a></li>
        <li><a href="#section2">Configuraciones</a></li>
      </ul><br>      
    </div>

<div class="login">
  <div class="container">
    <div class="form">
    <div class="col-sm-4">
    </div>
    <div class="col-sm-3 text-center">
    <h1>Usuario</h1>    
      <%= form_for(@user) do |f| %>
        <%= f.text_field :nombre, :placeholder => "Nombre" ,class:"form-control"%><br>
        <%= f.text_field :apellido, :placeholder => "Apellido" ,class:"form-control"%><br>
        <%= f.password_field :password, :placeholder => "Password" ,class:"form-control"%><br>
        <%= f.password_field :password_confirmation, :placeholder => "Password" ,class:"form-control"%><br>
        <%= f.submit "Guardar", class: "btn-submit btn btn-success" %>      
        <a href="/ibc" class="btn btn-warning">Cancelar</a>
      <% end %>
      </div>
    </div>
  </div>
</div>

  </div>
</div>